project_id = "czejdbdwaumbdepiswcu"

[functions.oculivo-ai]
verify_jwt = true

[functions.oculivo-support-api]
verify_jwt = true

[functions.phone-session]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.universal-esign]
verify_jwt = false

[functions.send-fax]
verify_jwt = false

[functions.receive-sms]
verify_jwt = false

[functions.receive-email]
verify_jwt = false
