
import { useEffect, useRef, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { MessageSquareText, Mic, Phone, PhoneOff, RefreshCw, Send } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Lang='en'|'es'
type Row=Record<string,any>
const t=(v:any)=>v==null?'':String(v)
const localized=(v:any,lang:Lang)=>{
 const raw=t(v),k=raw.toLowerCase().replace(/[ -]+/g,'_')
 if(lang!=='es')return raw
 const m:Record<string,string>={idle:'Inactivo',preparing:'Preparando',ringing:'Llamando',connected:'Conectada',ended:'Finalizada',error:'Error',open:'Abierto',closed:'Cerrado',active:'Activo',email:'Correo',sms:'SMS',phone:'Teléfono'}
 return m[k]||raw
}

function useOrgAccess(session:Session){
  const [orgId,setOrgId]=useState(localStorage.getItem('oculivo-org-id')||'')
  const [role,setRole]=useState('')
  useEffect(()=>{const f=(e:any)=>setOrgId(String(e?.detail||localStorage.getItem('oculivo-org-id')||''));window.addEventListener('oculivo-org-change',f);return()=>window.removeEventListener('oculivo-org-change',f)},[])
  useEffect(()=>{let active=true;(async()=>{const q=supabase.from('organization_memberships').select('organization_id,role,is_active').eq('user_id',session.user.id).eq('is_active',true);const r=orgId?await q.eq('organization_id',orgId).maybeSingle():await q.limit(1).maybeSingle();if(!active)return;if(r.data?.organization_id){const id=String(r.data.organization_id);localStorage.setItem('oculivo-org-id',id);setOrgId(id);setRole(String(r.data.role||''))}else setRole('')})();return()=>{active=false}},[session.user.id,orgId])
  return {orgId,role,canCommunicate:['owner','admin','manager','provider','staff'].includes(role)}
}

export function InboxComms({session,lang}:{session:Session;lang:Lang}){
 const {orgId,canCommunicate}=useOrgAccess(session),[threads,setThreads]=useState<Row[]>([]),[threadId,setThreadId]=useState(''),[messages,setMessages]=useState<Row[]>([]),[body,setBody]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function loadThreads(){if(!orgId)return;const r=await supabase.from('communication_threads').select('*').eq('organization_id',orgId).order('last_message_at',{ascending:false,nullsFirst:false}).limit(200);if(r.error){setError(r.error.message);return}setThreads(r.data||[]);if(!threadId&&r.data?.[0]?.id)setThreadId(String(r.data[0].id))}
 async function loadMessages(id=threadId){if(!orgId||!id){setMessages([]);return}const r=await supabase.from('communication_messages').select('*').eq('organization_id',orgId).eq('thread_id',id).order('created_at',{ascending:true}).limit(500);if(r.error){setError(r.error.message);return}setMessages(r.data||[]);const unread=(r.data||[]).filter(x=>x.direction==='inbound'&&!x.is_read).map(x=>x.id);if(canCommunicate&&unread.length)await supabase.from('communication_messages').update({is_read:true}).eq('organization_id',orgId).in('id',unread)}
 useEffect(()=>{void loadThreads()},[orgId])
 useEffect(()=>{void loadMessages(threadId)},[threadId,orgId])
 const active=threads.find(x=>String(x.id)===threadId)
 async function send(e:any){e.preventDefault();if(!active||!body.trim()||busy||!canCommunicate)return;setBusy(true);setError('');const channel=String(active.channel);const fn=channel==='sms'?'send-sms':channel==='email'?'send-email':'';if(!fn){setError(lang==='es'?'Este canal no admite respuestas desde la bandeja.':'This channel does not support inbox replies.');setBusy(false);return}const r=await supabase.functions.invoke(fn,{body:{thread_id:threadId,body:body.trim(),subject:active.subject||undefined}});if(r.error||r.data?.error){const raw=String(r.data?.error||r.error?.message||'');const missing=/not found|404|function/i.test(raw);setError(missing?(lang==='es'?'El servicio de envío todavía no está desplegado en el backend.':'The messaging backend function is not deployed yet.'):(raw||(lang==='es'?'No se pudo enviar el mensaje.':'Send failed')))}else{setBody('');await Promise.all([loadMessages(threadId),loadThreads()])}setBusy(false)}
 return <section><div className="wf-head"><div><h2>{lang==='es'?'Bandeja unificada':'Unified inbox'}</h2><p>{lang==='es'?'Correo y SMS por consultorio':'Practice-scoped email and SMS'}</p></div><button className="refresh-button" onClick={()=>void loadThreads()}><RefreshCw size={14}/>{lang==='es'?'Actualizar':'Refresh'}</button></div>{error&&<div className="wf-alert">{error}</div>}<div className="inbox-workspace"><aside className="inbox-thread-list">{!threads.length&&<div className="inbox-empty"><MessageSquareText size={20}/><strong>{lang==='es'?'Sin conversaciones todavía':'No conversations yet'}</strong><p>{lang==='es'?'Los hilos de correo y SMS aparecerán aquí.':'Email and SMS threads will appear here.'}</p></div>}{threads.map(x=><button key={x.id} className={threadId===String(x.id)?'active':''} onClick={()=>setThreadId(String(x.id))}><strong>{x.subject||x.phone_number||x.email_address||(lang==='es'?'Conversación':'Conversation')}</strong><span>{localized(x.channel,lang)} · {localized(x.status,lang)}</span></button>)}</aside><div className="inbox-thread"><header><div><h3>{active?.subject||active?.phone_number||active?.email_address||(lang==='es'?'Conversación':'Conversation')}</h3><span>{localized(active?.channel||'',lang)}</span></div></header><div className="inbox-messages">{messages.map(m=><article key={m.id} className={m.direction==='outbound'?'message-bubble outbound':'message-bubble'}><div><strong>{m.sender_name||(m.direction==='outbound'?(lang==='es'?'Consultorio':'Practice'):(lang==='es'?'Paciente':'Patient'))}</strong><span>{new Date(m.created_at).toLocaleString()}</span></div><p>{m.body}</p></article>)}</div>{active&&canCommunicate&&(String(active.channel)==='sms'||String(active.channel)==='email')?<form className="inbox-compose" onSubmit={send}><textarea rows={2} value={body} onChange={e=>setBody(e.target.value)} placeholder={lang==='es'?'Escribe una respuesta…':'Write a reply…'}/><button type="submit" disabled={busy||!body.trim()}><Send size={15}/>{busy?(lang==='es'?'Enviando…':'Sending…'):(lang==='es'?'Enviar':'Send')}</button></form>:<div className="inbox-readonly-note">{!canCommunicate?(lang==='es'?'Tu rol tiene acceso de solo lectura.':'Your role has read-only access.'):(lang==='es'?'Selecciona un hilo de correo o SMS para responder.':'Select an email or SMS thread to reply.')}</div>}</div></div></section>
}

const SDK_URL='https://esm.sh/@signalwire/js@4.0.0-rc.2?bundle'

export function PhoneOps({session,lang}:{session:Session;lang:Lang}){
 const {orgId,canCommunicate}=useOrgAccess(session),[threads,setThreads]=useState<Row[]>([]),[threadId,setThreadId]=useState(''),[status,setStatus]=useState<'idle'|'preparing'|'ringing'|'connected'|'ended'|'error'>('idle'),[destination,setDestination]=useState(''),[error,setError]=useState('')
 const audioRef=useRef<HTMLAudioElement>(null),clientRef=useRef<any>(null),callRef=useRef<any>(null),messageIdRef=useRef('')
 async function load(){if(!orgId)return;const r=await supabase.from('communication_threads').select('*').eq('organization_id',orgId).eq('channel','phone').order('last_message_at',{ascending:false,nullsFirst:false}).limit(200);if(r.error){setError(r.error.message);return}setThreads(r.data||[]);if(!threadId&&r.data?.[0]?.id)setThreadId(String(r.data[0].id))}
 useEffect(()=>{void load()},[orgId])
 async function cleanup(){try{await clientRef.current?.destroy?.()}catch{}clientRef.current=null;callRef.current=null;if(audioRef.current)audioRef.current.srcObject=null}
 async function report(action:string){if(!messageIdRef.current)return;await supabase.functions.invoke('phone-session',{body:{action,message_id:messageIdRef.current}})}
 async function start(){if(!threadId){setError(lang==='es'?'Selecciona una conversación telefónica primero.':'Select a phone conversation first.');return}if(!canCommunicate){setError(lang==='es'?'Tu rol tiene acceso telefónico de solo lectura.':'Your role has read-only phone access.');return}setStatus('preparing');setError('');const prep=await supabase.functions.invoke('phone-session',{body:{action:'prepare',thread_id:threadId}});if(prep.error||prep.data?.error||!prep.data?.token){const raw=String(prep.data?.error||prep.error?.message||'');const missing=/not found|404|function/i.test(raw);setError(missing?(lang==='es'?'El servicio telefónico todavía no está desplegado en el backend.':'The phone backend function is not deployed yet.'):(raw||(lang==='es'?'No se pudo preparar la llamada.':'Could not prepare call')));setStatus('error');return}try{messageIdRef.current=String(prep.data.message_id||'');setDestination(String(prep.data.destination||''));const sdk:any=await import(/* @vite-ignore */ SDK_URL);const provider=new sdk.StaticCredentialProvider({token:prep.data.token});const client=new sdk.SignalWire(provider);clientRef.current=client;const call=await client.dial(prep.data.destination,{audio:true,video:false});callRef.current=call;setStatus('ringing');call.remoteStream$.subscribe((stream:MediaStream|null)=>{if(audioRef.current&&stream){audioRef.current.srcObject=stream;audioRef.current.play().catch(()=>undefined)}});call.status$.subscribe(async(next:string)=>{if(next==='connected'){setStatus('connected');await report('connected')}if(next==='ringing'||next==='trying')setStatus('ringing');if(next==='disconnected'||next==='ended'){setStatus('ended');await report('complete');await cleanup()}})}catch(e:any){setError(e?.message||(lang==='es'?'La llamada falló.':'Phone call failed'));setStatus('error');await report('failed');await cleanup()}}
 async function hangup(){try{await callRef.current?.hangup?.()}finally{setStatus('ended');await report('complete');await cleanup()}}
 const active=threads.find(x=>String(x.id)===threadId),inCall=['preparing','ringing','connected'].includes(status)
 return <section><audio ref={audioRef} autoPlay playsInline/><div className="wf-head"><div><h2>{lang==='es'?'Teléfono':'Phone'}</h2><p>{lang==='es'?'Llamadas del consultorio desde el navegador':'Practice calls from your browser'}</p></div><button className="refresh-button" onClick={()=>void load()}><RefreshCw size={14}/>{lang==='es'?'Actualizar':'Refresh'}</button></div>{error&&<div className="wf-alert">{error}</div>}<div className="phone-workspace"><aside className="inbox-thread-list">{!threads.length&&<div className="inbox-empty"><Phone size={20}/><strong>{lang==='es'?'Sin conversaciones telefónicas':'No phone conversations'}</strong><p>{lang==='es'?'Los hilos telefónicos aparecerán aquí cuando estén disponibles.':'Phone threads will appear here when available.'}</p></div>}{threads.map(x=><button key={x.id} className={threadId===String(x.id)?'active':''} onClick={()=>{setThreadId(String(x.id));setStatus('idle');setError('')}}><strong>{x.subject||x.phone_number||(lang==='es'?'Conversación telefónica':'Phone conversation')}</strong><span>{x.phone_number||''}</span></button>)}</aside><div className="phone-dialer-card"><div className={'phone-orb '+status}><Phone size={28}/></div><span className="date-kicker">{localized(status,lang).toUpperCase()}</span><h2>{active?.phone_number||destination|| (lang==='es'?'Selecciona un hilo':'Select a phone thread')}</h2><p>{status==='connected'?(lang==='es'?'Llamada conectada':'Call connected'):status==='ringing'?(lang==='es'?'Llamando…':'Ringing…'):status==='preparing'?(lang==='es'?'Preparando sesión segura…':'Preparing secure session…'):(lang==='es'?'Usa el micrófono de este navegador para llamar desde la identidad telefónica del consultorio.':'Uses this browser microphone and the practice phone identity.')}</p>{!inCall?<button className="wf-primary" disabled={!threadId||!canCommunicate} onClick={()=>void start()}><Phone size={16}/>{status==='ended'||status==='error'?(lang==='es'?'Llamar otra vez':'Call again'):(lang==='es'?'Iniciar llamada':'Start call')}</button>:<button className="wf-danger" disabled={status==='preparing'} onClick={()=>void hangup()}><PhoneOff size={16}/>{lang==='es'?'Colgar':'Hang up'}</button>}<div className="phone-mic-note"><Mic size={13}/>{!canCommunicate?(lang==='es'?'Tu rol tiene acceso de solo lectura.':'Your role has read-only access.'):(lang==='es'?'El navegador pedirá permiso para usar el micrófono.':'Your browser will ask for microphone permission.')}</div></div></div></section>
}
