
import { useEffect, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { Plus, Save, Trash2, X, Clock } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Lang='en'|'es'
type Row=Record<string,any>
type Org={organizationId:string;role:string;organizationName:string}
const s=(v:any)=>v==null?'':String(v)
const n=(v:any)=>Number.isFinite(Number(v))?Number(v):0
const writer=(r:string)=>['owner','admin','provider','manager','staff','billing'].includes(r)
const clinician=(r:string)=>['owner','admin','provider','manager'].includes(r)

function useOrg(session:Session){
  const [org,setOrg]=useState<Org|null>(null),[error,setError]=useState(''),[v,setV]=useState(0)
  useEffect(()=>{const f=()=>setV(x=>x+1);window.addEventListener('oculivo-org-change',f);return()=>window.removeEventListener('oculivo-org-change',f)},[])
  useEffect(()=>{let a=true;(async()=>{
    const m=await supabase.from('organization_memberships').select('organization_id,role,is_active').eq('user_id',session.user.id).eq('is_active',true)
    if(!a)return
    if(m.error||!m.data?.length){setError(m.error?.message||'No active practice membership.');return}
    const wanted=localStorage.getItem('oculivo-org-id')||''
    const mem=m.data.find(x=>s(x.organization_id)===wanted)||m.data[0]
    const id=s(mem.organization_id);localStorage.setItem('oculivo-org-id',id)
    const o=await supabase.from('organizations').select('name').eq('id',id).maybeSingle()
    if(!a)return
    if(o.error){setError(o.error.message);return}
    setOrg({organizationId:id,role:s(mem.role)||'staff',organizationName:s(o.data?.name)||'Practice'})
  })();return()=>{a=false}},[session.user.id,v])
  return {org,error}
}
function useRows(table:string,orgId?:string,order='created_at'){
  const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState('')
  async function load(){if(!orgId)return;let q=supabase.from(table).select('*').eq('organization_id',orgId);if(order)q=q.order(order,{ascending:false});const r=await q.limit(200);if(r.error)setError(r.error.message);else{setError('');setRows(r.data||[])}}
  useEffect(()=>{void load()},[table,orgId]);return {rows,error,load}
}
function Field({label,children}:{label:string;children:any}){return <label className="wf-field"><span>{label}</span>{children}</label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:any}){return <div className="wf-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="wf-modal"><header><h2>{title}</h2><button onClick={onClose}><X size={18}/></button></header>{children}</section></div>}
function Alert({text}:{text:string}){return text?<div className="wf-alert">{text}</div>:null}
function Head({title,sub,button,onClick,disabled=false}:{title:string;sub:string;button:string;onClick:()=>void;disabled?:boolean}){return <div className="wf-head"><div><h2>{title}</h2><p>{sub}</p></div><button className="wf-primary" onClick={onClick} disabled={disabled}><Plus size={15}/>{button}</button></div>}
function PatientSelect({value,setValue,rows}:{value:string;setValue:(v:string)=>void;rows:Row[]}){return <select required value={value} onChange={e=>setValue(e.target.value)}><option value="">Select patient</option>{rows.map(p=><option key={p.id} value={p.id}>{s(p.first_name)+' '+s(p.last_name)}</option>)}</select>}

export function PatientsOps({session,lang}:{session:Session;lang:Lang}){
 const {org,error:oe}=useOrg(session),d=useRows('patients',org?.organizationId),[open,setOpen]=useState(false),[edit,setEdit]=useState<Row|null>(null),[f,setF]=useState<Row>({}),[msg,setMsg]=useState('')
 function start(r?:Row){setEdit(r||null);setF(r?{...r}:{first_name:'',last_name:'',preferred_name:'',date_of_birth:'',email:'',phone:'',preferred_language:'en',notes:''});setMsg('');setOpen(true)}
 async function save(e:any){e.preventDefault();if(!org)return;const p={first_name:s(f.first_name).trim(),last_name:s(f.last_name).trim(),preferred_name:s(f.preferred_name)||null,date_of_birth:s(f.date_of_birth)||null,email:s(f.email)||null,phone:s(f.phone)||null,preferred_language:s(f.preferred_language)||'en',notes:s(f.notes)||null};const r=edit?await supabase.from('patients').update(p).eq('id',edit.id).eq('organization_id',org.organizationId):await supabase.from('patients').insert({organization_id:org.organizationId,...p});if(r.error)setMsg(r.error.message);else{setOpen(false);await d.load()}}
 async function archive(r:Row){if(!org||!confirm('Archive this patient?'))return;const q=await supabase.from('patients').update({status:'archived'}).eq('id',r.id).eq('organization_id',org.organizationId);if(q.error)setMsg(q.error.message);else await d.load()}
 return <><Head title={lang==='es'?'Pacientes':'Patients'} sub={org?.organizationName||''} button={lang==='es'?'Nuevo paciente':'New patient'} onClick={()=>start()} disabled={!org||!writer(org.role)}/><Alert text={oe||d.error||msg}/><div className="wf-grid">{d.rows.map(r=><article className="wf-card" key={r.id}><div><h3>{s(r.first_name)+' '+s(r.last_name)}</h3><span className="status-badge">{s(r.status)}</span></div><p>{[r.email,r.phone,r.date_of_birth].filter(Boolean).join(' · ')||'—'}</p><footer><button onClick={()=>start(r)}>Edit</button>{r.status!=='archived'&&<button className="danger-link" onClick={()=>void archive(r)}>Archive</button>}</footer></article>)}</div>{open&&<Modal title={edit?'Edit patient':'New patient'} onClose={()=>setOpen(false)}><form className="wf-form" onSubmit={save}><div className="wf-two"><Field label="First name"><input required value={s(f.first_name)} onChange={e=>setF({...f,first_name:e.target.value})}/></Field><Field label="Last name"><input required value={s(f.last_name)} onChange={e=>setF({...f,last_name:e.target.value})}/></Field></div><div className="wf-two"><Field label="Preferred name"><input value={s(f.preferred_name)} onChange={e=>setF({...f,preferred_name:e.target.value})}/></Field><Field label="Date of birth"><input type="date" value={s(f.date_of_birth)} onChange={e=>setF({...f,date_of_birth:e.target.value})}/></Field></div><div className="wf-two"><Field label="Email"><input type="email" value={s(f.email)} onChange={e=>setF({...f,email:e.target.value})}/></Field><Field label="Phone"><input value={s(f.phone)} onChange={e=>setF({...f,phone:e.target.value})}/></Field></div><Field label="Language"><select value={s(f.preferred_language)||'en'} onChange={e=>setF({...f,preferred_language:e.target.value})}><option value="en">English</option><option value="es">Español</option></select></Field><Field label="Notes"><textarea rows={4} value={s(f.notes)} onChange={e=>setF({...f,notes:e.target.value})}/></Field><Alert text={msg}/><button className="wf-primary full"><Save size={15}/>Save patient</button></form></Modal>}</>
}

export function ScheduleOps({session,lang}:{session:Session;lang:Lang}){
 const {org,error:oe}=useOrg(session),a=useRows('appointments',org?.organizationId,'starts_at'),p=useRows('patients',org?.organizationId),pr=useRows('providers',org?.organizationId),lo=useRows('locations',org?.organizationId),[open,setOpen]=useState(false),[edit,setEdit]=useState<Row|null>(null),[f,setF]=useState<Row>({}),[msg,setMsg]=useState('')
 const local=(v:any)=>{if(!v)return'';const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
 function start(r?:Row){setEdit(r||null);setF(r?{...r,starts_at:local(r.starts_at),ends_at:local(r.ends_at)}:{patient_id:'',provider_id:'',location_id:'',appointment_type:'Comprehensive eye exam',starts_at:'',ends_at:'',room:'',notes:''});setMsg('');setOpen(true)}
 async function save(e:any){e.preventDefault();if(!org)return;const payload={patient_id:f.patient_id,provider_id:f.provider_id||null,location_id:f.location_id||null,appointment_type:s(f.appointment_type),starts_at:new Date(f.starts_at).toISOString(),ends_at:new Date(f.ends_at).toISOString(),room:s(f.room)||null,notes:s(f.notes)||null,created_by:session.user.id};const r=edit?await supabase.from('appointments').update(payload).eq('id',edit.id).eq('organization_id',org.organizationId):await supabase.from('appointments').insert({organization_id:org.organizationId,...payload});if(r.error)setMsg(r.error.message);else{setOpen(false);await a.load()}}
 async function del(r:Row){if(!org||!confirm('Delete this appointment?'))return;const q=await supabase.from('appointments').delete().eq('id',r.id).eq('organization_id',org.organizationId);if(q.error)setMsg(q.error.message);else await a.load()}
 const pn=(id:any)=>{const x=p.rows.find(q=>q.id===id);return x?s(x.first_name)+' '+s(x.last_name):'Patient'}
 return <><Head title={lang==='es'?'Agenda':'Schedule'} sub={org?.organizationName||''} button={lang==='es'?'Nueva cita':'New appointment'} onClick={()=>start()} disabled={!org||!writer(org.role)}/><Alert text={oe||a.error||msg}/><div className="wf-list">{a.rows.map(r=><article className="wf-row" key={r.id}><div className="wf-date"><b>{new Date(r.starts_at).toLocaleDateString()}</b><span>{new Date(r.starts_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</span></div><div className="wf-grow"><h3>{pn(r.patient_id)}</h3><p>{s(r.appointment_type)+(r.room?' · '+s(r.room):'')}</p></div><span className="status-badge">{s(r.status)}</span><button onClick={()=>start(r)}>Edit</button><button className="icon-danger" onClick={()=>void del(r)}><Trash2 size={14}/></button></article>)}</div>{open&&<Modal title={edit?'Edit appointment':'New appointment'} onClose={()=>setOpen(false)}><form className="wf-form" onSubmit={save}><Field label="Patient"><PatientSelect value={s(f.patient_id)} setValue={v=>setF({...f,patient_id:v})} rows={p.rows}/></Field><div className="wf-two"><Field label="Provider"><select value={s(f.provider_id)} onChange={e=>setF({...f,provider_id:e.target.value})}><option value="">Unassigned</option>{pr.rows.map(x=><option key={x.id} value={x.id}>{x.display_name}</option>)}</select></Field><Field label="Location"><select value={s(f.location_id)} onChange={e=>setF({...f,location_id:e.target.value})}><option value="">Default</option>{lo.rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field></div><Field label="Appointment type"><input required value={s(f.appointment_type)} onChange={e=>setF({...f,appointment_type:e.target.value})}/></Field><div className="wf-two"><Field label="Starts"><input type="datetime-local" required value={s(f.starts_at)} onChange={e=>setF({...f,starts_at:e.target.value})}/></Field><Field label="Ends"><input type="datetime-local" required value={s(f.ends_at)} onChange={e=>setF({...f,ends_at:e.target.value})}/></Field></div><Field label="Room"><input value={s(f.room)} onChange={e=>setF({...f,room:e.target.value})}/></Field><Field label="Notes"><textarea rows={3} value={s(f.notes)} onChange={e=>setF({...f,notes:e.target.value})}/></Field><Alert text={msg}/><button className="wf-primary full"><Save size={15}/>Save appointment</button></form></Modal>}</>
}

export function ClinicalOps({session,lang}:{session:Session;lang:Lang}){
 const {org,error:oe}=useOrg(session),d=useRows('clinical_records',org?.organizationId),p=useRows('patients',org?.organizationId),pr=useRows('providers',org?.organizationId),[open,setOpen]=useState(false),[edit,setEdit]=useState<Row|null>(null),[f,setF]=useState<Row>({}),[msg,setMsg]=useState('')
 function start(r?:Row){setEdit(r||null);setF(r?{...r}:{patient_id:'',provider_id:'',chief_complaint:'',visual_acuity_od:'',visual_acuity_os:'',iop_od:'',iop_os:'',assessment:'',treatment_plan:''});setMsg('');setOpen(true)}
 async function save(e:any){e.preventDefault();if(!org)return;const q={patient_id:f.patient_id,provider_id:f.provider_id||null,chief_complaint:s(f.chief_complaint)||null,visual_acuity_od:s(f.visual_acuity_od)||null,visual_acuity_os:s(f.visual_acuity_os)||null,iop_od:s(f.iop_od)||null,iop_os:s(f.iop_os)||null,assessment:s(f.assessment)||null,treatment_plan:s(f.treatment_plan)||null,created_by:session.user.id};const r=edit?await supabase.from('clinical_records').update(q).eq('id',edit.id).eq('organization_id',org.organizationId):await supabase.from('clinical_records').insert({organization_id:org.organizationId,...q});if(r.error)setMsg(r.error.message);else{setOpen(false);await d.load()}}
 async function sign(r:Row){if(!org)return;const q=await supabase.from('clinical_records').update({signed_at:new Date().toISOString()}).eq('id',r.id).eq('organization_id',org.organizationId);if(q.error)setMsg(q.error.message);else await d.load()}
 const pn=(id:any)=>{const x=p.rows.find(q=>q.id===id);return x?s(x.first_name)+' '+s(x.last_name):'Patient'}
 return <><Head title={lang==='es'?'Clínica':'Clinical'} sub={org?.organizationName||''} button={lang==='es'?'Nuevo registro':'New record'} onClick={()=>start()} disabled={!org||!clinician(org.role)}/><Alert text={oe||d.error||msg}/><div className="wf-grid">{d.rows.map(r=><article className="wf-card" key={r.id}><div><h3>{pn(r.patient_id)}</h3><span className="status-badge">{r.signed_at?'Signed':'Draft'}</span></div><p>{r.chief_complaint||r.assessment||'Clinical record'}</p><div className="clinical-mini"><span>VA OD<b>{r.visual_acuity_od||'—'}</b></span><span>VA OS<b>{r.visual_acuity_os||'—'}</b></span><span>IOP OD<b>{r.iop_od||'—'}</b></span><span>IOP OS<b>{r.iop_os||'—'}</b></span></div><footer><button onClick={()=>start(r)}>Edit</button>{!r.signed_at&&<button onClick={()=>void sign(r)}>Sign</button>}</footer></article>)}</div>{open&&<Modal title={edit?'Edit clinical record':'New clinical record'} onClose={()=>setOpen(false)}><form className="wf-form" onSubmit={save}><Field label="Patient"><PatientSelect value={s(f.patient_id)} setValue={v=>setF({...f,patient_id:v})} rows={p.rows}/></Field><Field label="Provider"><select value={s(f.provider_id)} onChange={e=>setF({...f,provider_id:e.target.value})}><option value="">Unassigned</option>{pr.rows.map(x=><option key={x.id} value={x.id}>{x.display_name}</option>)}</select></Field><Field label="Chief complaint"><textarea rows={2} value={s(f.chief_complaint)} onChange={e=>setF({...f,chief_complaint:e.target.value})}/></Field><div className="wf-four"><Field label="VA OD"><input value={s(f.visual_acuity_od)} onChange={e=>setF({...f,visual_acuity_od:e.target.value})}/></Field><Field label="VA OS"><input value={s(f.visual_acuity_os)} onChange={e=>setF({...f,visual_acuity_os:e.target.value})}/></Field><Field label="IOP OD"><input value={s(f.iop_od)} onChange={e=>setF({...f,iop_od:e.target.value})}/></Field><Field label="IOP OS"><input value={s(f.iop_os)} onChange={e=>setF({...f,iop_os:e.target.value})}/></Field></div><Field label="Assessment"><textarea rows={3} value={s(f.assessment)} onChange={e=>setF({...f,assessment:e.target.value})}/></Field><Field label="Treatment plan"><textarea rows={3} value={s(f.treatment_plan)} onChange={e=>setF({...f,treatment_plan:e.target.value})}/></Field><Alert text={msg}/><button className="wf-primary full"><Save size={15}/>Save record</button></form></Modal>}</>
}

export function TimeclockOps({session,lang}:{session:Session;lang:Lang}){
 const {org,error:oe}=useOrg(session),d=useRows('time_entries',org?.organizationId,'clock_in'),[msg,setMsg]=useState('')
 const mine=d.rows.filter(r=>r.user_id===session.user.id),open=mine.find(r=>!r.clock_out)
 async function punch(){if(!org)return;const r=open?await supabase.from('time_entries').update({clock_out:new Date().toISOString()}).eq('id',open.id).eq('organization_id',org.organizationId):await supabase.from('time_entries').insert({organization_id:org.organizationId,user_id:session.user.id,clock_in:new Date().toISOString()});if(r.error)setMsg(r.error.message);else await d.load()}
 return <><div className="timeclock-hero"><div><span>{lang==='es'?'ESTADO ACTUAL':'CURRENT STATUS'}</span><h2>{open?(lang==='es'?'En turno':'Clocked in'):(lang==='es'?'Fuera de turno':'Clocked out')}</h2><p>{open?'Since '+new Date(open.clock_in).toLocaleString():(lang==='es'?'Listo para iniciar tu turno.':'Ready to start your shift.')}</p></div><button className={open?'wf-danger':'wf-primary'} onClick={()=>void punch()}><Clock size={16}/>{open?(lang==='es'?'Marcar salida':'Clock out'):(lang==='es'?'Marcar entrada':'Clock in')}</button></div><Alert text={oe||d.error||msg}/><div className="wf-list">{mine.map(r=><article className="wf-row" key={r.id}><div className="wf-grow"><h3>{new Date(r.clock_in).toLocaleDateString()}</h3><p>{new Date(r.clock_in).toLocaleTimeString()+' → '+(r.clock_out?new Date(r.clock_out).toLocaleTimeString():'Active')}</p></div><span className="status-badge">{r.clock_out?'Complete':'Active'}</span></article>)}</div></>
}

export function SupportOps({session,lang}:{session:Session;lang:Lang}){
 const {org,error:oe}=useOrg(session),d=useRows('support_tickets',org?.organizationId),[open,setOpen]=useState(false),[f,setF]=useState<Row>({}),[msg,setMsg]=useState('')
 function start(){setF({subject:'',description:'',category:'technical',priority:'normal'});setOpen(true);setMsg('')}
 async function save(e:any){e.preventDefault();if(!org)return;const r=await supabase.from('support_tickets').insert({organization_id:org.organizationId,submitted_by:session.user.id,subject:f.subject,description:f.description,category:f.category||'technical',priority:f.priority||'normal',current_page:window.location.pathname});if(r.error)setMsg(r.error.message);else{setOpen(false);await d.load()}}
 return <><Head title={lang==='es'?'Soporte':'Support'} sub={lang==='es'?'Tickets enviados a RomyLabs':'Tickets routed to RomyLabs'} button={lang==='es'?'Nuevo ticket':'New ticket'} onClick={start} disabled={!org}/><Alert text={oe||d.error||msg}/><div className="wf-list">{d.rows.map(r=><article className="wf-row" key={r.id}><div className="wf-grow"><h3>{r.subject}</h3><p>{s(r.category)+' · '+new Date(r.created_at).toLocaleString()}</p></div><span className="status-badge">{r.priority}</span><span className="status-badge">{r.status}</span></article>)}</div>{open&&<Modal title={lang==='es'?'Nuevo ticket':'New support ticket'} onClose={()=>setOpen(false)}><form className="wf-form" onSubmit={save}><Field label="Subject"><input required value={s(f.subject)} onChange={e=>setF({...f,subject:e.target.value})}/></Field><Field label="Description"><textarea rows={6} required value={s(f.description)} onChange={e=>setF({...f,description:e.target.value})}/></Field><div className="wf-two"><Field label="Category"><select value={s(f.category)} onChange={e=>setF({...f,category:e.target.value})}><option value="technical">Technical</option><option value="billing">Billing</option><option value="feature_request">Feature request</option><option value="training">Training</option><option value="other">Other</option></select></Field><Field label="Priority"><select value={s(f.priority)} onChange={e=>setF({...f,priority:e.target.value})}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></Field></div><Alert text={msg}/><button className="wf-primary full"><Save size={15}/>Submit ticket</button></form></Modal>}</>
}
